const ACTION_START = "ACTION_START"
const FETCH_SUCCESS = "FETCH_SUCCESS"
const FETCH_FAIL = "FETCH_FAIL"
const SET_FETCHED_NEWS = "SET_FETCHED_NEWS"
const SET_BOOKMARKS = "SET_BOOKMARKS"
const FETCH_BOOKMARKS_START = "FETCH_BOOKMARKS_START"
const REMOVE_FROM_BOOKMARKS = "REMOVE_FROM_BOOKMARKS"

export {
    ACTION_START,
    FETCH_SUCCESS,
    FETCH_FAIL,
    SET_FETCHED_NEWS,
    FETCH_BOOKMARKS_START,
    SET_BOOKMARKS,
    REMOVE_FROM_BOOKMARKS
}