const FETCH_NEWS_START = "FETCH_NEWS_START"
const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS"
const FETCH_NEWS_FAIL = "FETCH_NEWS_FAIL"
const SET_FETCHED_NEWS = "SET_FETCHED_NEWS"

export {
    FETCH_NEWS_START,
    FETCH_NEWS_SUCCESS,
    FETCH_NEWS_FAIL,
    SET_FETCHED_NEWS
}